#!/usr/bin/env bash
# A Bash script that runs indefinitely and ignores the CTRL+C signal

# Ignore SIGINT (CTRL+C)
trap "" SIGINT

# Infinite loop
while true; do
    echo "Don't stop me now"
    sleep 2
done
