#!/usr/bin/env bash
# This script displays "Best School" 10 times
# and displays "Hi" on the 9th iteration

for i in {1..10}
do
  if [ "$i" -eq 9 ]
  then
    echo "Hi"
  else
    echo "Best School"
  fi
done
